name: 'Trigger CircleCI Job'
author: 'Simon Swan'
description: 'Trigger a specific CircleCi job. Code modified from zivkaziv/circleci-trigger-github-action.'
branding:
  icon: 'truck'
  color: 'purple'
inputs:
  token:
    description: 'CircleCI Api Token'
    required: true
  org:
    description: 'CircleCI organization name'
    required: false
  repo:
    description: 'Repository name - by default will use the current repository name'
    required: false
  branch:
    description: 'Branch name - by default will use the current branch name'
    required: false
  job:
    description: 'CircleCI job name'
    required: true
runs:
  using: 'node12'
  main: './dist/index.js'
